
package com.example.duws.proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b05 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DuWebService", targetNamespace = "http://duws.orsyp.com", wsdlLocation = "file:/C:/app/perso/Data/Repositories/eclipse-javaee-workspace/webapp5/src/wsdl/duws61051.wsdl")
public class DuWebService_Service
    extends Service
{

    private final static URL DUWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException DUWEBSERVICE_EXCEPTION;
    private final static QName DUWEBSERVICE_QNAME = new QName("http://duws.orsyp.com", "DuWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/app/perso/Data/Repositories/eclipse-javaee-workspace/webapp5/src/wsdl/duws61051.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DUWEBSERVICE_WSDL_LOCATION = url;
        DUWEBSERVICE_EXCEPTION = e;
    }

    public DuWebService_Service() {
        super(__getWsdlLocation(), DUWEBSERVICE_QNAME);
    }

    public DuWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), DUWEBSERVICE_QNAME, features);
    }

    public DuWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, DUWEBSERVICE_QNAME);
    }

    public DuWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DUWEBSERVICE_QNAME, features);
    }

    public DuWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DuWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DuWebService
     */
    @WebEndpoint(name = "DuWebServicePort")
    public DuWebService getDuWebServicePort() {
        return super.getPort(new QName("http://duws.orsyp.com", "DuWebServicePort"), DuWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DuWebService
     */
    @WebEndpoint(name = "DuWebServicePort")
    public DuWebService getDuWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://duws.orsyp.com", "DuWebServicePort"), DuWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DUWEBSERVICE_EXCEPTION!= null) {
            throw DUWEBSERVICE_EXCEPTION;
        }
        return DUWEBSERVICE_WSDL_LOCATION;
    }

}
