
package com.example.duws.proxy;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b05 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "DuwsException", targetNamespace = "http://duws.orsyp.com")
public class DuwsException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DuwsException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public DuwsException_Exception(String message, DuwsException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public DuwsException_Exception(String message, DuwsException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.example.duws.proxy.DuwsException
     */
    public DuwsException getFaultInfo() {
        return faultInfo;
    }

}
