
package com.webops.duws.proxy;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b05 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DuWebService", targetNamespace = "http://duws.orsyp.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DuWebService {


    /**
     * 
     * @param executionId
     * @param context
     * @return
     *     returns com.webops.duws.proxy.Execution
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @WebResult(name = "execution", targetNamespace = "http://duws.orsyp.com")
    @RequestWrapper(localName = "getExecution", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetExecution")
    @ResponseWrapper(localName = "getExecutionResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetExecutionResponse")
    public Execution getExecution(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "executionId", targetNamespace = "http://duws.orsyp.com")
        ExecutionId executionId)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param eventId
     * @param context
     * @return
     *     returns com.webops.duws.proxy.Event
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @WebResult(name = "event", targetNamespace = "http://duws.orsyp.com")
    @RequestWrapper(localName = "getEvent", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetEvent")
    @ResponseWrapper(localName = "getEventResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetEventResponse")
    public Event getEvent(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "eventId", targetNamespace = "http://duws.orsyp.com")
        EventId eventId)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param outage
     * @param context
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createOutageWindow", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.CreateOutageWindow")
    @ResponseWrapper(localName = "createOutageWindowResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.CreateOutageWindowResponse")
    public void createOutageWindow(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "outage", targetNamespace = "http://duws.orsyp.com", mode = WebParam.Mode.INOUT)
        Holder<OutageWindow> outage)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param variables
     * @param context
     * @param taskId
     * @return
     *     returns com.webops.duws.proxy.LaunchId
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @WebResult(name = "launchId", targetNamespace = "http://duws.orsyp.com")
    @RequestWrapper(localName = "addLaunchFromTask2", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.AddLaunchFromTask2")
    @ResponseWrapper(localName = "addLaunchFromTask2Response", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.AddLaunchFromTask2Response")
    public LaunchId addLaunchFromTask2(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "taskId", targetNamespace = "http://duws.orsyp.com")
        TaskId taskId,
        @WebParam(name = "variables", targetNamespace = "http://duws.orsyp.com")
        List<Variable> variables)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param launchId
     * @param context
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteLaunch", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.DeleteLaunch")
    @ResponseWrapper(localName = "deleteLaunchResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.DeleteLaunchResponse")
    public void deleteLaunch(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "launchId", targetNamespace = "http://duws.orsyp.com")
        LaunchId launchId)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param launchId
     * @param context
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "releaseLaunch", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.ReleaseLaunch")
    @ResponseWrapper(localName = "releaseLaunchResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.ReleaseLaunchResponse")
    public void releaseLaunch(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "launchId", targetNamespace = "http://duws.orsyp.com")
        LaunchId launchId)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param filter
     * @param context
     * @return
     *     returns java.util.List<com.webops.duws.proxy.ExecutionItem>
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @WebResult(name = "executionList", targetNamespace = "http://duws.orsyp.com")
    @RequestWrapper(localName = "getListExecution", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetListExecution")
    @ResponseWrapper(localName = "getListExecutionResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetListExecutionResponse")
    public List<ExecutionItem> getListExecution(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "filter", targetNamespace = "http://duws.orsyp.com")
        ExecutionFilter filter)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param token
     * @throws DuwsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "logout", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.LogoutResponse")
    public void logout(
        @WebParam(name = "token", targetNamespace = "http://duws.orsyp.com")
        String token)
        throws DuwsException_Exception
    ;

    /**
     * 
     * @param context
     * @param event
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "addEvent", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.AddEvent")
    @ResponseWrapper(localName = "addEventResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.AddEventResponse")
    public void addEvent(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "event", targetNamespace = "http://duws.orsyp.com")
        Event event)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param executionId
     * @param byPassCheck
     * @param endDate
     * @param batchQueue
     * @param context
     * @param step
     * @param uvmsConnection
     * @param startDate
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "rerunExecution", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.RerunExecution")
    @ResponseWrapper(localName = "rerunExecutionResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.RerunExecutionResponse")
    public void rerunExecution(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "executionId", targetNamespace = "http://duws.orsyp.com")
        ExecutionId executionId,
        @WebParam(name = "startDate", targetNamespace = "http://duws.orsyp.com")
        String startDate,
        @WebParam(name = "endDate", targetNamespace = "http://duws.orsyp.com")
        String endDate,
        @WebParam(name = "batchQueue", targetNamespace = "http://duws.orsyp.com")
        String batchQueue,
        @WebParam(name = "uvmsConnection", targetNamespace = "http://duws.orsyp.com")
        String uvmsConnection,
        @WebParam(name = "step", targetNamespace = "http://duws.orsyp.com")
        int step,
        @WebParam(name = "byPassCheck", targetNamespace = "http://duws.orsyp.com")
        boolean byPassCheck)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param eventId
     * @param context
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteEvent", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.DeleteEvent")
    @ResponseWrapper(localName = "deleteEventResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.DeleteEventResponse")
    public void deleteEvent(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "eventId", targetNamespace = "http://duws.orsyp.com")
        EventId eventId)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param outage
     * @param context
     * @return
     *     returns java.util.List<com.webops.duws.proxy.OutageWindow>
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListOutage", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetListOutage")
    @ResponseWrapper(localName = "getListOutageResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetListOutageResponse")
    public List<OutageWindow> getListOutage(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "outage", targetNamespace = "http://duws.orsyp.com")
        OutageFilter outage)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param launchId
     * @param context
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "acknowledgeExecution", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.AcknowledgeExecution")
    @ResponseWrapper(localName = "acknowledgeExecutionResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.AcknowledgeExecutionResponse")
    public void acknowledgeExecution(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "launchId", targetNamespace = "http://duws.orsyp.com")
        LaunchId launchId)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param launchId
     * @param context
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "unacknowledgeExecution", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.UnacknowledgeExecution")
    @ResponseWrapper(localName = "unacknowledgeExecutionResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.UnacknowledgeExecutionResponse")
    public void unacknowledgeExecution(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "launchId", targetNamespace = "http://duws.orsyp.com")
        LaunchId launchId)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param executionId
     * @param delay
     * @param context
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "stopExecution", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.StopExecution")
    @ResponseWrapper(localName = "stopExecutionResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.StopExecutionResponse")
    public void stopExecution(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "executionId", targetNamespace = "http://duws.orsyp.com")
        ExecutionId executionId,
        @WebParam(name = "delay", targetNamespace = "http://duws.orsyp.com")
        int delay)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param context
     * @param launch
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateLaunch", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.UpdateLaunch")
    @ResponseWrapper(localName = "updateLaunchResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.UpdateLaunchResponse")
    public void updateLaunch(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "launch", targetNamespace = "http://duws.orsyp.com")
        Launch launch)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param context
     * @param launch
     * @return
     *     returns com.webops.duws.proxy.LaunchId
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @WebResult(name = "launchId", targetNamespace = "http://duws.orsyp.com")
    @RequestWrapper(localName = "addLaunch", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.AddLaunch")
    @ResponseWrapper(localName = "addLaunchResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.AddLaunchResponse")
    public LaunchId addLaunch(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "launch", targetNamespace = "http://duws.orsyp.com")
        Launch launch)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param filter
     * @param context
     * @return
     *     returns java.util.List<com.webops.duws.proxy.SessionItem>
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @WebResult(name = "sessionList", targetNamespace = "http://duws.orsyp.com")
    @RequestWrapper(localName = "getListSession", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetListSession")
    @ResponseWrapper(localName = "getListSessionResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetListSessionResponse")
    public List<SessionItem> getListSession(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "filter", targetNamespace = "http://duws.orsyp.com")
        SessionFilter filter)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param launchId
     * @param context
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "skipExecution", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.SkipExecution")
    @ResponseWrapper(localName = "skipExecutionResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.SkipExecutionResponse")
    public void skipExecution(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "launchId", targetNamespace = "http://duws.orsyp.com")
        LaunchId launchId)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param filter
     * @param context
     * @return
     *     returns java.util.List<com.webops.duws.proxy.TaskItem>
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @WebResult(name = "taskList", targetNamespace = "http://duws.orsyp.com")
    @RequestWrapper(localName = "getListTask", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetListTask")
    @ResponseWrapper(localName = "getListTaskResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetListTaskResponse")
    public List<TaskItem> getListTask(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "filter", targetNamespace = "http://duws.orsyp.com")
        TaskFilter filter)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.webops.duws.proxy.DuwsVersion
     * @throws DuwsException_Exception
     */
    @WebMethod
    @WebResult(name = "version", targetNamespace = "http://duws.orsyp.com")
    @RequestWrapper(localName = "getWsVersion", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetWsVersion")
    @ResponseWrapper(localName = "getWsVersionResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetWsVersionResponse")
    public DuwsVersion getWsVersion()
        throws DuwsException_Exception
    ;

    /**
     * 
     * @param outage
     * @param context
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteOutageWindow", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.DeleteOutageWindow")
    @ResponseWrapper(localName = "deleteOutageWindowResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.DeleteOutageWindowResponse")
    public void deleteOutageWindow(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "outage", targetNamespace = "http://duws.orsyp.com")
        OutageWindow outage)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param eventId
     * @param context
     * @param step
     * @param status
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateEvent", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.UpdateEvent")
    @ResponseWrapper(localName = "updateEventResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.UpdateEventResponse")
    public void updateEvent(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "eventId", targetNamespace = "http://duws.orsyp.com")
        EventId eventId,
        @WebParam(name = "status", targetNamespace = "http://duws.orsyp.com")
        String status,
        @WebParam(name = "step", targetNamespace = "http://duws.orsyp.com")
        String step)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param context
     * @param runBookFilter
     * @return
     *     returns java.util.List<com.webops.duws.proxy.RunBook>
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @WebResult(name = "runbooks", targetNamespace = "http://duws.orsyp.com")
    @RequestWrapper(localName = "getRunBooks", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetRunBooks")
    @ResponseWrapper(localName = "getRunBooksResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetRunBooksResponse")
    public List<RunBook> getRunBooks(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "runBookFilter", targetNamespace = "http://duws.orsyp.com")
        RunBookFilter runBookFilter)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param executionId
     * @param context
     * @return
     *     returns com.webops.duws.proxy.ResourceLog
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @WebResult(name = "resourceLog", targetNamespace = "http://duws.orsyp.com")
    @RequestWrapper(localName = "getScriptResourceLog", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetScriptResourceLog")
    @ResponseWrapper(localName = "getScriptResourceLogResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetScriptResourceLogResponse")
    public ResourceLog getScriptResourceLog(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "executionId", targetNamespace = "http://duws.orsyp.com")
        ExecutionId executionId)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param executionId
     * @param context
     * @return
     *     returns java.util.List<com.webops.duws.proxy.PreviousLaunch>
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @WebResult(name = "previousLaunches", targetNamespace = "http://duws.orsyp.com")
    @RequestWrapper(localName = "getPreviousLaunches", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetPreviousLaunches")
    @ResponseWrapper(localName = "getPreviousLaunchesResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetPreviousLaunchesResponse")
    public List<PreviousLaunch> getPreviousLaunches(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "executionId", targetNamespace = "http://duws.orsyp.com")
        ExecutionId executionId)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param engine
     * @param context
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "stopEngine", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.StopEngine")
    @ResponseWrapper(localName = "stopEngineResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.StopEngineResponse")
    public void stopEngine(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "engine", targetNamespace = "http://duws.orsyp.com")
        Engine engine)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param filter
     * @param context
     * @return
     *     returns java.util.List<com.webops.duws.proxy.NodeItem>
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @WebResult(name = "nodeList", targetNamespace = "http://duws.orsyp.com")
    @RequestWrapper(localName = "getListNode", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetListNode")
    @ResponseWrapper(localName = "getListNodeResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetListNodeResponse")
    public List<NodeItem> getListNode(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "filter", targetNamespace = "http://duws.orsyp.com")
        NodeFilter filter)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param context
     * @param taskId
     * @return
     *     returns com.webops.duws.proxy.Launch
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @WebResult(name = "launch", targetNamespace = "http://duws.orsyp.com")
    @RequestWrapper(localName = "getLaunchFromTask", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetLaunchFromTask")
    @ResponseWrapper(localName = "getLaunchFromTaskResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetLaunchFromTaskResponse")
    public Launch getLaunchFromTask(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "taskId", targetNamespace = "http://duws.orsyp.com")
        TaskId taskId)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param context
     * @param queue
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "startQueue", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.StartQueue")
    @ResponseWrapper(localName = "startQueueResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.StartQueueResponse")
    public void startQueue(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "queue", targetNamespace = "http://duws.orsyp.com")
        Queue queue)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param engine
     * @param context
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "restartEngine", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.RestartEngine")
    @ResponseWrapper(localName = "restartEngineResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.RestartEngineResponse")
    public void restartEngine(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "engine", targetNamespace = "http://duws.orsyp.com")
        Engine engine)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param executionId
     * @param context
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "purgeExecution", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.PurgeExecution")
    @ResponseWrapper(localName = "purgeExecutionResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.PurgeExecutionResponse")
    public void purgeExecution(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "executionId", targetNamespace = "http://duws.orsyp.com")
        ExecutionId executionId)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param engine
     * @param context
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "startEngine", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.StartEngine")
    @ResponseWrapper(localName = "startEngineResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.StartEngineResponse")
    public void startEngine(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "engine", targetNamespace = "http://duws.orsyp.com")
        Engine engine)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param launchId
     * @param context
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "bypassLaunchConditionCheck", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.BypassLaunchConditionCheck")
    @ResponseWrapper(localName = "bypassLaunchConditionCheckResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.BypassLaunchConditionCheckResponse")
    public void bypassLaunchConditionCheck(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "launchId", targetNamespace = "http://duws.orsyp.com")
        LaunchId launchId)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param uvms
     * @return
     *     returns java.lang.String
     * @throws DuwsException_Exception
     */
    @WebMethod
    @WebResult(name = "token", targetNamespace = "http://duws.orsyp.com")
    @RequestWrapper(localName = "login", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.LoginResponse")
    public String login(
        @WebParam(name = "uvms", targetNamespace = "http://duws.orsyp.com")
        UvmsContext uvms)
        throws DuwsException_Exception
    ;

    /**
     * 
     * @param context
     * @param queue
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "resetQueue", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.ResetQueue")
    @ResponseWrapper(localName = "resetQueueResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.ResetQueueResponse")
    public void resetQueue(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "queue", targetNamespace = "http://duws.orsyp.com")
        Queue queue)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param context
     * @param queue
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "stopQueue", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.StopQueue")
    @ResponseWrapper(localName = "stopQueueResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.StopQueueResponse")
    public void stopQueue(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "queue", targetNamespace = "http://duws.orsyp.com")
        Queue queue)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param nodeFilter
     * @param token
     * @return
     *     returns java.util.List<com.webops.duws.proxy.Envir>
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @WebResult(name = "envList", targetNamespace = "http://duws.orsyp.com")
    @RequestWrapper(localName = "getDUEnvironmentList", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetDUEnvironmentList")
    @ResponseWrapper(localName = "getDUEnvironmentListResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetDUEnvironmentListResponse")
    public List<Envir> getDUEnvironmentList(
        @WebParam(name = "token", targetNamespace = "http://duws.orsyp.com")
        String token,
        @WebParam(name = "nodeFilter", targetNamespace = "http://duws.orsyp.com")
        UvmsNodeFilter nodeFilter)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param filter
     * @param context
     * @return
     *     returns java.util.List<com.webops.duws.proxy.MuItem>
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @WebResult(name = "muList", targetNamespace = "http://duws.orsyp.com")
    @RequestWrapper(localName = "getListMU", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetListMU")
    @ResponseWrapper(localName = "getListMUResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetListMUResponse")
    public List<MuItem> getListMU(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "filter", targetNamespace = "http://duws.orsyp.com")
        MuFilter filter)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param launchId
     * @param context
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "disableLaunch", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.DisableLaunch")
    @ResponseWrapper(localName = "disableLaunchResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.DisableLaunchResponse")
    public void disableLaunch(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "launchId", targetNamespace = "http://duws.orsyp.com")
        LaunchId launchId)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param executionId
     * @param context
     * @return
     *     returns byte[]
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @WebResult(name = "dataHandler", targetNamespace = "http://duws.orsyp.com")
    @RequestWrapper(localName = "getExecutionLogAsAttachment", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetExecutionLogAsAttachment")
    @ResponseWrapper(localName = "getExecutionLogAsAttachmentResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetExecutionLogAsAttachmentResponse")
    public byte[] getExecutionLogAsAttachment(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "executionId", targetNamespace = "http://duws.orsyp.com")
        ExecutionId executionId)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param launchId
     * @param context
     * @return
     *     returns com.webops.duws.proxy.Launch
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @WebResult(name = "launch", targetNamespace = "http://duws.orsyp.com")
    @RequestWrapper(localName = "getLaunch", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetLaunch")
    @ResponseWrapper(localName = "getLaunchResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetLaunchResponse")
    public Launch getLaunch(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "launchId", targetNamespace = "http://duws.orsyp.com")
        LaunchId launchId)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param executionId
     * @param context
     * @return
     *     returns com.webops.duws.proxy.ExecutionLog
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @WebResult(name = "executionLog", targetNamespace = "http://duws.orsyp.com")
    @RequestWrapper(localName = "getExecutionLog", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetExecutionLog")
    @ResponseWrapper(localName = "getExecutionLogResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetExecutionLogResponse")
    public ExecutionLog getExecutionLog(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "executionId", targetNamespace = "http://duws.orsyp.com")
        ExecutionId executionId)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param executionId
     * @param context
     * @return
     *     returns com.webops.duws.proxy.HistoryTrace
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @WebResult(name = "historyTrace", targetNamespace = "http://duws.orsyp.com")
    @RequestWrapper(localName = "getHistoryTrace", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetHistoryTrace")
    @ResponseWrapper(localName = "getHistoryTraceResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetHistoryTraceResponse")
    public HistoryTrace getHistoryTrace(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "executionId", targetNamespace = "http://duws.orsyp.com")
        ExecutionId executionId)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param launchId
     * @param context
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "enableLaunch", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.EnableLaunch")
    @ResponseWrapper(localName = "enableLaunchResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.EnableLaunchResponse")
    public void enableLaunch(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "launchId", targetNamespace = "http://duws.orsyp.com")
        LaunchId launchId)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param filter
     * @param context
     * @return
     *     returns java.util.List<com.webops.duws.proxy.LaunchItem>
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @WebResult(name = "launchList", targetNamespace = "http://duws.orsyp.com")
    @RequestWrapper(localName = "getListLaunch", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetListLaunch")
    @ResponseWrapper(localName = "getListLaunchResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetListLaunchResponse")
    public List<LaunchItem> getListLaunch(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "filter", targetNamespace = "http://duws.orsyp.com")
        LaunchFilter filter)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param context
     * @param noteFilter
     * @return
     *     returns java.util.List<com.webops.duws.proxy.RunNote>
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @WebResult(name = "runNotes", targetNamespace = "http://duws.orsyp.com")
    @RequestWrapper(localName = "getRunNotes", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetRunNotes")
    @ResponseWrapper(localName = "getRunNotesResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetRunNotesResponse")
    public List<RunNote> getRunNotes(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "noteFilter", targetNamespace = "http://duws.orsyp.com")
        RunNoteFilter noteFilter)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param context
     * @param sessionItem
     * @return
     *     returns com.webops.duws.proxy.SessionTree
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @WebResult(name = "sessionTree", targetNamespace = "http://duws.orsyp.com")
    @RequestWrapper(localName = "getSessionTree", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetSessionTree")
    @ResponseWrapper(localName = "getSessionTreeResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetSessionTreeResponse")
    public SessionTree getSessionTree(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "sessionItem", targetNamespace = "http://duws.orsyp.com")
        SessionItem sessionItem)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param filter
     * @param context
     * @return
     *     returns java.util.List<com.webops.duws.proxy.EventItem>
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @WebResult(name = "eventList", targetNamespace = "http://duws.orsyp.com")
    @RequestWrapper(localName = "getListEvent", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetListEvent")
    @ResponseWrapper(localName = "getListEventResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetListEventResponse")
    public List<EventItem> getListEvent(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "filter", targetNamespace = "http://duws.orsyp.com")
        EventFilter filter)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param context
     * @param runBook
     * @return
     *     returns byte[]
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @WebResult(name = "fileDataHandler", targetNamespace = "http://duws.orsyp.com")
    @RequestWrapper(localName = "getRunBookExternalFile", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetRunBookExternalFile")
    @ResponseWrapper(localName = "getRunBookExternalFileResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetRunBookExternalFileResponse")
    public byte[] getRunBookExternalFile(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "runBook", targetNamespace = "http://duws.orsyp.com")
        RunBook runBook)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param launchId
     * @param context
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "forceCompleteLaunch", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.ForceCompleteLaunch")
    @ResponseWrapper(localName = "forceCompleteLaunchResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.ForceCompleteLaunchResponse")
    public void forceCompleteLaunch(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "launchId", targetNamespace = "http://duws.orsyp.com")
        LaunchId launchId)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param filter
     * @param context
     * @return
     *     returns java.util.List<com.webops.duws.proxy.UprocItem>
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @WebResult(name = "uprocList", targetNamespace = "http://duws.orsyp.com")
    @RequestWrapper(localName = "getListUproc", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetListUproc")
    @ResponseWrapper(localName = "getListUprocResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.GetListUprocResponse")
    public List<UprocItem> getListUproc(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "filter", targetNamespace = "http://duws.orsyp.com")
        UprocFilter filter)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param context
     * @param launch
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "holdLaunch", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.HoldLaunch")
    @ResponseWrapper(localName = "holdLaunchResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.HoldLaunchResponse")
    public void holdLaunch(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "launch", targetNamespace = "http://duws.orsyp.com")
        LaunchId launch)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

    /**
     * 
     * @param context
     * @param taskId
     * @return
     *     returns com.webops.duws.proxy.LaunchId
     * @throws SessionTimedOutException_Exception
     * @throws DuwsException_Exception
     */
    @WebMethod
    @WebResult(name = "launchId", targetNamespace = "http://duws.orsyp.com")
    @RequestWrapper(localName = "addLaunchFromTask", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.AddLaunchFromTask")
    @ResponseWrapper(localName = "addLaunchFromTaskResponse", targetNamespace = "http://duws.orsyp.com", className = "com.webops.duws.proxy.AddLaunchFromTaskResponse")
    public LaunchId addLaunchFromTask(
        @WebParam(name = "context", targetNamespace = "http://duws.orsyp.com")
        ContextHolder context,
        @WebParam(name = "taskId", targetNamespace = "http://duws.orsyp.com")
        TaskId taskId)
        throws DuwsException_Exception, SessionTimedOutException_Exception
    ;

}
