
package com.webops.duws.proxy;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b05 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "SessionTimedOutException", targetNamespace = "http://duws.orsyp.com")
public class SessionTimedOutException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SessionTimedOutException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SessionTimedOutException_Exception(String message, SessionTimedOutException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public SessionTimedOutException_Exception(String message, SessionTimedOutException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.webops.duws.proxy.SessionTimedOutException
     */
    public SessionTimedOutException getFaultInfo() {
        return faultInfo;
    }

}
